#!/usr/bin/env bash
# Regenerates DIRECTORY.md from the project file tree.
# Called automatically by the Claude Code PostToolUse hook after Write/Edit.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO_ROOT/DIRECTORY.md"

# Files/dirs to exclude from the listing
PRUNE_DIRS=(".git" "target" ".idea" ".DS_Store")

build_prune_args() {
  local args=()
  for d in "${PRUNE_DIRS[@]}"; do
    args+=(-path "*/$d" -prune -o)
  done
  echo "${args[@]}"
}

# Extract a short description from the first meaningful comment in a file.
# Returns "—" for binary files or when nothing is found.
describe() {
  local file="$1"
  local ext="${file##*.}"

  # Binary files
  case "$ext" in
    bam|bai|class|jar|png|jpg|jpeg|gif|zip|gz)
      echo "Binary file"
      return
      ;;
  esac

  # Read first 40 lines for comment extraction
  local head
  head="$(head -n 40 "$file" 2>/dev/null)" || { echo "—"; return; }

  case "$ext" in
    java)
      # First /** javadoc block (single line extract) or first // comment
      local javadoc
      javadoc="$(echo "$head" | grep -m1 '^ *\*' | sed 's/^ *\* *//' | tr -d '\r')"
      if [[ -n "$javadoc" && "$javadoc" != "/" ]]; then
        echo "$javadoc"
        return
      fi
      local slashslash
      slashslash="$(echo "$head" | grep -m1 '^ *//' | sed 's|^ *// *||' | tr -d '\r')"
      [[ -n "$slashslash" ]] && echo "$slashslash" || echo "—"
      ;;
    xml)
      local comment
      comment="$(echo "$head" | grep -o '<!--[^-]*' | head -1 | sed 's/<!--[[:space:]]*//' | tr -d '\r')"
      [[ -n "$comment" ]] && echo "$comment" || echo "—"
      ;;
    py)
      # Skip shebang; take first # comment or first docstring line
      local pycomment
      pycomment="$(echo "$head" | grep -v '^#!' | grep -m1 '^#' | sed 's/^#[[:space:]]*//' | tr -d '\r')"
      if [[ -n "$pycomment" ]]; then
        echo "$pycomment"
        return
      fi
      local docstring
      docstring="$(echo "$head" | grep -m1 '"""' | sed 's/.*"""\(.*\)/\1/' | tr -d '\r')"
      [[ -n "$docstring" ]] && echo "$docstring" || echo "—"
      ;;
    sh)
      # Skip shebang; take first # comment
      local shcomment
      shcomment="$(echo "$head" | grep -v '^#!' | grep -m1 '^#' | sed 's/^#[[:space:]]*//' | tr -d '\r')"
      [[ -n "$shcomment" ]] && echo "$shcomment" || echo "—"
      ;;
    md)
      # First heading or first non-empty line
      local heading
      heading="$(echo "$head" | grep -m1 '^#' | sed 's/^#* *//' | tr -d '\r')"
      [[ -n "$heading" ]] && echo "$heading" || echo "—"
      ;;
    *)
      # Dockerfile, .gitignore, service files, etc. — first # comment (skip shebang)
      local generic
      generic="$(echo "$head" | grep -v '^#!' | grep -m1 '^#' | sed 's/^#[[:space:]]*//' | tr -d '\r')"
      [[ -n "$generic" ]] && echo "$generic" || echo "—"
      ;;
  esac
}

# Rough token estimate: bytes / 4 (standard approximation for LLM tokenizers).
# Binary files show byte size only.
token_count() {
  local file="$1"
  local ext="${file##*.}"
  case "$ext" in
    bam|bai|class|jar|png|jpg|jpeg|gif|zip|gz)
      echo "—"
      return
      ;;
  esac
  local bytes
  bytes="$(wc -c < "$file" 2>/dev/null)" || { echo "—"; return; }
  echo "$(( (bytes + 3) / 4 ))"
}

human_size() {
  local bytes="$1"
  if   (( bytes >= 1048576 )); then printf "%.1f MB" "$(echo "scale=1; $bytes/1048576" | bc)"
  elif (( bytes >= 1024 ));    then printf "%.1f KB" "$(echo "scale=1; $bytes/1024" | bc)"
  else                              printf "%d B" "$bytes"
  fi
}

{
  echo "# Directory"
  echo ""
  echo "Auto-generated by \`scripts/generate-directory.sh\`. Do not edit by hand."
  echo ""
  echo "| File | Description | Size | ~Tokens |"
  echo "|---|---|---|---|"

  # Build find command dynamically
  find "$REPO_ROOT" \
    -path "$REPO_ROOT/.git" -prune -o \
    -path "$REPO_ROOT/target" -prune -o \
    -path "$REPO_ROOT/.idea" -prune -o \
    -path "*/target" -prune -o \
    -type f -print \
  | sort \
  | while IFS= read -r abs; do
      rel="${abs#$REPO_ROOT/}"

      # Skip DIRECTORY.md itself to avoid circular descriptions
      [[ "$rel" == "DIRECTORY.md" ]] && continue

      bytes="$(wc -c < "$abs" 2>/dev/null || echo 0)"
      size="$(human_size "$bytes")"
      desc="$(describe "$abs")"
      tokens="$(token_count "$abs")"

      printf "| \`%s\` | %s | %s | %s |\n" "$rel" "$desc" "$size" "$tokens"
    done
} > "$OUT"

echo "DIRECTORY.md updated ($(wc -l < "$OUT") lines)" >&2
